# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Sit Next To' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sit Next To
  pod 'Google-Mobile-Ads-SDK'

  target 'Sit Next ToTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sit Next ToUITests' do
    # Pods for testing
  end

end
